remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Evidencias W2

nombres: Sergio Daniel Marenco Cerpa
submodulo: Programación Web II
periodo: 2023-2
url_foto: https://scontent.feoh5-1.fna.fbcdn.net/v/t39.30808-6/289156964_152553643987395_600570545045115860_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=5f2048&_nc_ohc=O5kOTmZvNwIAX_IJMUg&_nc_ht=scontent.feoh5-1.fna&oh=00_AfCkxq-biPYm8PTrVuU_H3jbmia1VGeRVb_bxKlpz4C8NA&oe=654A7C39
